import { chromium, firefox, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const engine = process.env.TEST_BROWSER === 'firefox' ? firefox : chromium;
const browser = await engine.launch(engine === chromium ? {
  executablePath: process.env.CHROME_PATH || (existsSync('/usr/bin/google-chrome-stable')?'/usr/bin/google-chrome-stable':undefined),
  headless: true, args: ['--no-sandbox'],
} : { headless:true });
const url = process.env.TEST_URL || 'http://127.0.0.1:5173';
const errors=[];
try {
  const page=await browser.newPage({viewport:{width:1280,height:1080},acceptDownloads:true});
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(url);
  await page.locator('canvas[data-ready="true"]').waitFor();
  await expect(page.locator('html')).toHaveAttribute('lang','en');
  await expect(page.locator('#reset')).toHaveText('Restart');
  await expect(page.locator('#language')).toHaveText('DE');
  await page.locator('#language').click();
  await expect(page.locator('html')).toHaveAttribute('lang','de');
  await expect(page.locator('#reset')).toHaveText('Neustart');
  expect(await page.evaluate(()=>localStorage.getItem('stickman.language'))).toBe('de');
  await page.locator('#language').click();
  await expect(page.locator('html')).toHaveAttribute('lang','en');
  expect(await page.evaluate(()=>localStorage.getItem('stickman.language'))).toBe('en');
  await expect(page.getByRole('progressbar')).toHaveCount(6);
  await page.keyboard.press('F3');
  await page.keyboard.down('d');
  await expect(page.locator('#state-0')).toContainText('Walk');
  await page.waitForTimeout(1850);
  await page.keyboard.up('d');
  await page.keyboard.press('r');
  await expect(page.locator('#hp-1')).toHaveText('970 / 1000');
  await expect(page.locator('#resource-value-0-special')).toHaveText('3 / 100');
  await expect(page.locator('#resource-value-1-revenge')).toHaveText('3 / 100');
  await page.keyboard.press('F1');await page.keyboard.press('F2');
  await page.keyboard.press('p');
  const paused=Number(await page.locator('#game').getAttribute('data-frame'));
  await page.waitForTimeout(100);
  expect(Number(await page.locator('#game').getAttribute('data-frame'))).toBe(paused);
  await page.keyboard.press('.');
  await expect(page.locator('#game')).toHaveAttribute('data-frame',String(paused+1));
  await expect(page.locator('#input-0')).toContainText('LP');
  await page.keyboard.press('F4');await expect(page.locator('#timer')).toHaveText('∞');
  await page.keyboard.press('F5');await expect(page.locator('#dummy')).toContainText('Crouching');
  await page.keyboard.press('F5');await expect(page.locator('#dummy')).toContainText('Always block');
  await page.keyboard.press('F5');await expect(page.locator('#dummy')).toContainText('CPU');
  await expect(page.locator('#cpu-level')).toBeEnabled();
  await expect(page.locator('#arena-mode')).toContainText('TRAINING / CPU');
  await page.keyboard.press('F6');
  for(let i=0;i<10;i++)await page.keyboard.press('.');
  await page.keyboard.press('F6');
  const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export-replay').click()]);
  const replay=JSON.parse(await readFile(await download.path(),'utf8'));
  expect(replay.frames.length).toBe(10);
  expect(replay.initial.training.dummy).toBe('cpu');
  await page.keyboard.press('F7');
  await expect(page.locator('#notice')).toContainText('Replay ended');
  await page.keyboard.press('F7');
  await expect(page.locator('#notice')).toContainText('Back in the local game');
  await page.locator('#replay-file').setInputFiles({name:'replay.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(replay))});
  await expect(page.locator('#notice')).toContainText('Replay loaded');
  await page.locator('#settings-details summary').click();
  await page.locator('[data-player="0"][data-action="LP"]').click();await page.keyboard.press('u');
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('stickman.controls')).players[0].keys.LP)).toBe('KeyU');
  await page.locator('#settings-details summary').click();
  await page.screenshot({path:`/tmp/stickman-${engine===firefox?'firefox':'chrome'}-training.png`,fullPage:true});
  await page.reload();await page.locator('canvas[data-ready="true"]').waitFor();
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('stickman.controls')).players[0].keys.LP)).toBe('KeyU');
  await page.keyboard.press('u');await expect(page.locator('#state-0')).toContainText('standing_lp');
  await page.keyboard.press('p');
  await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
  await expect(page.locator('#pause')).toHaveText('Resume · P');
  await page.screenshot({path:`/tmp/stickman-${engine===firefox?'firefox':'chrome'}-final.png`,fullPage:true});
  await page.evaluate(()=>{
    window.testPad={id:'Simulated arcade stick',index:0,connected:true,mapping:'standard',timestamp:0,axes:[0,0],buttons:Array.from({length:20},()=>({value:0,pressed:false,touched:false}))};
    Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[window.testPad]});
  });
  await page.locator('#settings-details summary').click();
  await page.locator('[data-device="0"] option[value="0"]').waitFor({state:'attached'});
  await page.locator('[data-device="0"]').selectOption('0');
  await page.locator('#mapping-mode-0').selectOption('pad');
  await page.locator('[data-player="0"][data-action="LP"]').click();
  await page.waitForTimeout(50);
  await page.evaluate(()=>{window.testPad.buttons[10].pressed=true;window.testPad.buttons[10].value=1;});
  await expect(page.locator('[data-player="0"][data-action="LP"]')).toContainText('B10');
  await page.evaluate(()=>{window.testPad.buttons[10].pressed=false;window.testPad.buttons[10].value=0;});
  await page.locator('#settings-details summary').click();await page.keyboard.press('p');
  await page.evaluate(()=>{window.testPad.axes[0]=0.8;});
  await expect(page.locator('#state-0')).toContainText('Walk');
  await page.evaluate(()=>{window.testPad.axes[0]=0;});
  await expect(page.locator('#state-0')).toContainText('Idle');
  await page.evaluate(()=>{window.testPad.buttons[10].pressed=true;window.testPad.buttons[10].value=1;});
  await expect(page.locator('#state-0')).toContainText('standing_lp');
  await page.evaluate(()=>window.dispatchEvent(new Event('gamepaddisconnected')));
  await expect(page.locator('#notice')).toContainText('Controller disconnected');
  await expect(page.locator('#pause')).toHaveText('Resume · P');
  await page.setViewportSize({width:600,height:900});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  if(errors.length)throw Error(errors.join('\n'));
  console.log(`${engine===firefox?'Firefox':'Chrome'} smoke passed: language switching, combat, HUD, pause, frame step, training, replay export/import, remapping, simulated gamepad, focus and narrow layout.`);
} finally { await browser.close(); }
