import { previewMarkup } from '../debug/animation-preview';
import { stageSwitchMarkup } from './stage';
import { t } from './i18n';

const text=(key: Parameters<typeof t>[0])=>`data-i18n="${key}">${t(key)}`;
const aria=(key: Parameters<typeof t>[0])=>`data-i18n-aria-label="${key}" aria-label="${t(key)}"`;

export const markup = `
<main>
  <header><div class="brand"><div class="brand-mark">SF</div><div><h1>Stickman Fighter</h1><div class="eyebrow">Precision in every frame</div></div></div><div class="header-actions"><div class="status mono"><span class="dot"></span><span id="match-status">LOCAL VERSUS · 60 HZ</span></div><button id="language" type="button">DE</button><button id="theme" ${aria('theme.dark')} aria-pressed="false">☾</button></div></header>
  <div class="section-bar"><span class="eyebrow" ${text('section.arena')}</span><div class="section-actions">${stageSwitchMarkup}<strong class="mono" ${text('match.bestOfThree')}</strong></div></div>
  <div class="arena"><div class="hud"><div class="health-player"><div class="health-label mono"><strong id="p1-label">PLAYER 01</strong><span id="hp-0">1000 / 1000</span></div><div class="health-track" role="progressbar" ${aria('health.p1')} aria-valuemin="0" aria-valuemax="1000"><div id="health-0"></div></div><div id="wins-0" class="round-wins"></div></div><div class="timer-wrap"><div id="timer">99</div><span id="round-label" class="eyebrow">ROUND 01</span></div><div class="health-player player-two"><div class="health-label mono"><span id="hp-1">1000 / 1000</span><strong id="p2-label">PLAYER 02</strong></div><div class="health-track" role="progressbar" ${aria('health.p2')} aria-valuemin="0" aria-valuemax="1000"><div id="health-1"></div></div><div id="wins-1" class="round-wins"></div></div></div><canvas id="game" width="960" height="420" ${aria('arena.canvas')}></canvas><div class="resource-hud">${[0,1].map(i=>`<div class="resource-player ${i?'player-two':''}">${(['revenge','special'] as const).map(name=>`<div class="${name}"><div class="resource-label"><span>P${i+1} / ${name.toUpperCase()}</span><span id="resource-value-${i}-${name}">0 / 100</span></div><div id="resource-${i}-${name}" class="resource-track" role="progressbar" ${aria(`resource.p${i+1}${name==='revenge'?'Revenge':'Special'}` as Parameters<typeof t>[0])} aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="resource-fill"></div></div></div>`).join('')}</div>`).join('')}</div><div class="arena-caption mono"><span id="arena-mode">THE DOJO / LOCAL 1V1</span><span ${text('arena.tagline')}</span></div></div>
  <div class="toolbar"><div class="toolbar-group"><button id="pause" class="primary" ${text('button.pause')}</button><button id="step" disabled ${text('button.step')}</button><button id="reset" ${text('button.reset')}</button><button id="boxes" aria-pressed="false" ${text('button.boxes')}</button><button id="inputs" aria-pressed="false" ${text('button.inputs')}</button><button id="states" aria-pressed="false" ${text('button.states')}</button></div><span class="hint" ${text('controls.hint')}</span></div>
  <div class="training-bar"><div class="toolbar-group"><button id="training" aria-pressed="false" ${text('button.training')}</button><button id="dummy" disabled>Dummy: ${t('dummy.stand')} · F5</button><button id="cpu" aria-pressed="false">CPU: ${t('common.off')} · F8</button><button id="demo" aria-pressed="false">Demo: ${t('common.off')} · F9</button><label class="cpu-level" id="cpu-level-0-wrap">CPU 1 <select id="cpu-level-0" ${aria('difficulty.p1')}>${(['easy','medium','hard'] as const).map(level=>`<option value="${level}" data-i18n="difficulty.${level}">${t(`difficulty.${level}`)}</option>`).join('')}</select></label><label class="cpu-level">CPU 2 <select id="cpu-level" ${aria('difficulty.p2')}>${(['easy','medium','hard'] as const).map(level=>`<option value="${level}" data-i18n="difficulty.${level}">${t(`difficulty.${level}`)}</option>`).join('')}</select></label></div><div class="toolbar-group"><button id="record" ${text('button.record')}</button><button id="play" disabled ${text('button.replay')}</button><button id="export-replay" disabled ${text('button.save')}</button><button id="import-replay" ${text('button.load')}</button><input id="replay-file" type="file" accept="application/json,.json" hidden></div></div>
  <div class="controls">${[['01','W','A','S','D','R','T','Y','F','G','H','V','B','N'],['02','↑','←','↓','→','7','8','9','4','5','6','1','2','3']].map((k,i)=>`<div class="${i?'player-two':''}"><div class="player-label"><span></span>PLAYER ${k[0]} <small class="eyebrow" ${text(i?'controls.arrows':'controls.keyboard')}</small></div><div class="control-grid"><div class="keys"><i></i><kbd data-owner="${i}" data-control="up">${k[1]}</kbd><i></i><kbd data-owner="${i}" data-control="left">${k[2]}</kbd><kbd data-owner="${i}" data-control="down">${k[3]}</kbd><kbd data-owner="${i}" data-control="right">${k[4]}</kbd></div><div><div class="keys">${k.slice(5).map((key,index)=>`<kbd data-owner="${i}" data-control="${['LP','MP','HP','LK','LMK','HK','RLK','MK','RHK'][index]}">${key}</kbd>`).join('')}</div><div class="key-label mono"><span>LIGHT</span><span>MED</span><span>HEAVY</span></div></div><span class="hint" ${text('controls.limbs')}</span></div></div>`).join('')}</div>
  ${previewMarkup}
  <details id="settings-details"><summary ${text('settings.summary')}</summary><div id="settings"></div></details>
  <div class="debug" id="debug" hidden><pre id="state-0"></pre><pre id="state-1"></pre><pre id="cpu-debug" hidden></pre></div><div class="debug input-history" id="input-history" hidden><div><span class="eyebrow">P1 / <span ${text('input.latest')}</span></span><pre id="input-0"></pre></div><div><span class="eyebrow">P2 / <span ${text('input.latest')}</span></span><pre id="input-1"></pre></div></div>
  <div class="notice" id="notice" role="status"></div>
  <footer class="mono"><span ${text('footer.tagline')}</span><span>60 HZ SIMULATION / V1.4 · UPDATE 13</span></footer>
</main>`;
