import { previewMarkup } from '../debug/animation-preview';
import { stageSwitchMarkup } from './stage';
export const markup = `
<main>
  <header><div class="brand"><div class="brand-mark">SF</div><div><h1>Stickman Fighter</h1><div class="eyebrow">Precision in every frame</div></div></div><div class="header-actions"><div class="status mono"><span class="dot"></span><span id="match-status">LOCAL VERSUS · 60 HZ</span></div><button id="theme" aria-label="Dunkles Theme aktivieren" aria-pressed="false">☾</button></div></header>
  <div class="section-bar"><span class="eyebrow">01 / The arena</span><div class="section-actions">${stageSwitchMarkup}<strong class="mono">BEST OF THREE</strong></div></div>
  <div class="arena"><div class="hud"><div class="health-player"><div class="health-label mono"><strong id="p1-label">PLAYER 01</strong><span id="hp-0">1000 / 1000</span></div><div class="health-track" role="progressbar" aria-label="Spieler 1 Leben" aria-valuemin="0" aria-valuemax="1000"><div id="health-0"></div></div><div id="wins-0" class="round-wins"></div></div><div class="timer-wrap"><div id="timer">99</div><span id="round-label" class="eyebrow">ROUND 01</span></div><div class="health-player player-two"><div class="health-label mono"><span id="hp-1">1000 / 1000</span><strong id="p2-label">PLAYER 02</strong></div><div class="health-track" role="progressbar" aria-label="Spieler 2 Leben" aria-valuemin="0" aria-valuemax="1000"><div id="health-1"></div></div><div id="wins-1" class="round-wins"></div></div></div><canvas id="game" width="960" height="420" aria-label="Kampfarena für zwei Spieler"></canvas><div class="resource-hud">${[0,1].map(i=>`<div class="resource-player ${i?'player-two':''}">${['revenge','special'].map(name=>`<div class="${name}"><div class="resource-label"><span>P${i+1} / ${name==='revenge'?'REVENGE':'SPECIAL'}</span><span id="resource-value-${i}-${name}">0 / 100</span></div><div id="resource-${i}-${name}" class="resource-track" role="progressbar" aria-label="Spieler ${i+1} ${name==='revenge'?'Revenge':'Special'}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="resource-fill"></div></div></div>`).join('')}</div>`).join('')}</div><div class="arena-caption mono"><span id="arena-mode">THE DOJO / LOCAL 1V1</span><span>NO SHORTCUTS. JUST TIMING.</span></div></div>
  <div class="toolbar"><div class="toolbar-group"><button id="pause" class="primary">Pause · P</button><button id="step" disabled>Frame + · .</button><button id="reset">Neustart</button><button id="boxes" aria-pressed="false">Boxen · F1</button><button id="inputs" aria-pressed="false">Inputs · F2</button><button id="states" aria-pressed="false">Frames · F3</button></div><span class="hint">Zurück halten zum Blocken · ↑ Springen · ↓ Hocken · Zurück + MK/HK: Drehkick · Vorwärts + MK: Tornado · + HK: Spin · + MK und HK gleichzeitig: Kombo</span></div>
  <div class="training-bar"><div class="toolbar-group"><button id="training" aria-pressed="false">Training · F4</button><button id="dummy" disabled>Dummy: Stehen · F5</button><button id="cpu" aria-pressed="false">CPU: Aus · F8</button><button id="demo" aria-pressed="false">Demo: Aus · F9</button><label class="cpu-level" id="cpu-level-0-wrap">CPU 1 <select id="cpu-level-0" aria-label="CPU 1 Schwierigkeitsstufe"><option value="easy">Leicht</option><option value="medium">Mittel</option><option value="hard">Schwer</option></select></label><label class="cpu-level">CPU 2 <select id="cpu-level" aria-label="CPU 2 Schwierigkeitsstufe"><option value="easy">Leicht</option><option value="medium">Mittel</option><option value="hard">Schwer</option></select></label></div><div class="toolbar-group"><button id="record">● Aufnahme · F6</button><button id="play" disabled>Replay · F7</button><button id="export-replay" disabled>Speichern</button><button id="import-replay">Laden</button><input id="replay-file" type="file" accept="application/json,.json" hidden></div></div>
  <div class="controls">${[['01','W','A','S','D','R','T','Y','F','G','H','V','B','N'],['02','↑','←','↓','→','7','8','9','4','5','6','1','2','3']].map((k,i)=>`<div class="${i?'player-two':''}"><div class="player-label"><span></span>PLAYER ${k[0]} <small class="eyebrow">${i?'ARROWS + NUMPAD':'KEYBOARD'}</small></div><div class="control-grid"><div class="keys"><i></i><kbd data-owner="${i}" data-control="up">${k[1]}</kbd><i></i><kbd data-owner="${i}" data-control="left">${k[2]}</kbd><kbd data-owner="${i}" data-control="down">${k[3]}</kbd><kbd data-owner="${i}" data-control="right">${k[4]}</kbd></div><div><div class="keys">${k.slice(5).map((key,index)=>`<kbd data-owner="${i}" data-control="${['LP','MP','HP','LK','LMK','HK','RLK','MK','RHK'][index]}">${key}</kbd>`).join('')}</div><div class="key-label mono"><span>LIGHT</span><span>MED</span><span>HEAVY</span></div></div><span class="hint">Punches oben<br>Linkes Bein Mitte<br>Rechtes Bein unten</span></div></div>`).join('')}</div>
  ${previewMarkup}
  <details id="settings-details"><summary>Tasten & Controller konfigurieren</summary><div id="settings"></div></details>
  <div class="debug" id="debug" hidden><pre id="state-0"></pre><pre id="state-1"></pre><pre id="cpu-debug" hidden></pre></div><div class="debug input-history" id="input-history" hidden><div><span class="eyebrow">P1 / Neueste Eingabe oben</span><pre id="input-0"></pre></div><div><span class="eyebrow">P2 / Neueste Eingabe oben</span><pre id="input-1"></pre></div></div>
  <div class="notice" id="notice" role="status"></div>
  <footer class="mono"><span>NINE BUTTONS. TWO FIGHTERS. ONE WINNER.</span><span>60 HZ SIMULATION / V1.4 · UPDATE 13</span></footer>
</main>`;
